glasses/urls.py
from django.conf import settings
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^search/$', views.glasses_search, name='search'),
    url(r'^list/', views.search_results, name='list'),
    url(r'^add/$', views.glasses_add, name='add'),
]

optick/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from glasses import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page, name='index'),
    url(r'^glasses/', include('glasses.urls', namespace='glasses')),
    url(r'^sale/', include('sale.urls', namespace='sale')),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout')

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

sale/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.sale, name='glass_sale')
]

sale/models.py
from django.db import models
import datetime


class SoldGlasses(models.Model):
    kod = models.CharField(max_length=15)
    name = models.CharField(max_length=20, blank=True, null=True)
    dpt = models.FloatField(blank=True, null=True)
    pcs = models.IntegerField()
    sale_date = models.DateTimeField(auto_now_add=True)
    price_opt = models.FloatField()
    price_roz = models.IntegerField()
    glass_type = models.CharField(max_length=20, verbose_name='Тип')
    comment = models.TextField(blank=True, null=True)

    def date_filter(first_date, last_date):
        last_date = datetime.date(last_date.year, last_date.month, last_date.day+1)
        return SoldGlasses.objects.filter(sale_date__gte=first_date).exclude(sale_date__gte=last_date).order_by('-sale_date')

    def __str__(self):
        return '%s %s' % (self.name, self.kod)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="">

    <title>{% block title %}{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'bootstrap/css/starter-templ.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  {% block style %}{% endblock %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ОПТИКА</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="{% block active_main %}{% endblock %}"><a href="{% url 'index' %}">Головна</a></li>
          {% if user.username == 'nazar' %}
            <li class="{% block active_add %}{% endblock %}"><a href="{% url 'glasses:add' %}">Добавити</a></li>
          {% endif %}
            <li class="{% block active_search %}{% endblock %}"><a href="{% url 'glasses:search' %}">Пошук</a></li>
          </ul>
        <p class="navbar-text navbar-right">Ви авторизовані як <b>{{ user.username }}</b> <a href="{% url 'logout' %}">Вихід</a></p>
        </div>
      </div>
    </div>

    <div class="container">

      <div class="starter-template">
        {% block main_content %}
        {% endblock main_content %}
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}" ></script>
  </body>
</html>

templates/inc_glasses_list.html
<table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Код окулярів</th>
                  <th>Ім'я</th>
                  <th>Тип</th>
                  <th>Діоптрії</th>
                  <th>Кількість</th>
                  <th>Ціна</th>
                  {% if date %}<th>Дата, час продажу</th>{% endif %}
                  {% if sale %}<th></th>{% endif %}
                </tr>
              </thead>
              <tbody>
                {% for glass in glasses %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ glass.kod }}</td>
                  <td>{{ glass.name }}</td>
                  <td>{{ glass.get_glass_type_display }}</td>
                  <td>{% if glass.dpt %}{{ glass.dpt }}{% endif %}</td>
                  <td>{{ glass.pcs }}</td>
                  <td>{{ glass.price_roz }}</td>
                  {% if date %}
                    <td>{{ glass.sale_date|time }}, {{ glass.sale_date|date:"d.m.Y" }}</td>
                  {% endif %}
                  {% if not glass.sale_date %}
                      <td>
                        <a href="/sale/{{ glass.id }}" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-usd"></span> Продати</a>
                      </td>
                  {% endif %}
                </tr>
                {% endfor %}
                <tr>
                  <td colspan="5" align="center"><b>Всього</b></td>
                  <td><b>{{ sum_pcs }}</b></td>
                  <td colspan="2"><b>{{ sum_price }}</b></td>
                </tr>
              </tbody>
            </table>

templates/index.html
{% extends 'base.html' %}



{% block title %}Main page{% endblock title %}
{% block active_main %}active{% endblock  %}

{% block main_content %}
    {% if messages %}
        <div class="alert alert-success" align="left">
          <ul class="messages">
          {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
          </ul>
        </div>
    {% endif %}

      <form  method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" class="btn btn-default navbar-btn" value="Фільтрувати" />
  </form>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading" align="center"><h4> Статистика за 
  {% if first_date %}
  {{ first_date|date:"d.m" }} - {{ last_date|date:"d.m.Y" }}
  {% else %}
  {{ date|date:"d.m.Y" }}
  {% endif %}
</h4></div>

    {% include 'inc_glasses_list.html' %}

</div>


{% endblock main_content %}

templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html class="ex-ua-domain fex-login-page"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">

	<meta charset="utf-8">
	<title>Login</title>
{#	<link href="https://mail.ex.ua/v1/exmail5/favicon.ico" rel="shortcut icon" type="image/x-icon">#}
	<link href="{% static 'login_page/css.css' %}" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'login_page/vendors.css' %}">
	<link href="{% static 'login_page/main.css' %}" rel="stylesheet">

</head>

<body class="page no_touch">

    <div id="app" class="container fex-home">
        <div class="fex-header">
            <div class="fex-header__nav">  </div>
                <div class="fex-header__logo fex-mobile-hidden">
            <p class="fex-logo fex-logo--ex fex-logo--white"> ОПТИКА ТВОГО МІСТА</p>
                </div>
        </div>
        <div class="fex-login">
            <div class="fex-login__background fex-login__background--ex"></div>
            <div class="fex-login__backgroundShade"></div>
            <div class="fex-login__mask"></div>
            {% if login_error %}
                    <div class="note_wr" id="alert_box" style="display: block;">
                    <div class="note_bl">{{ login_error }}</div>
                    </div>
            {% endif %}
            <div class="fex-login__container">
                <h1 class="fex-login__headline"> Вхід для адміністраторів та продавців </h1>
                <div class="fex-login__form js-login-form"></div>
                    <p class="fex-login__formLabel" align="center"> Щоб увійти введіть Ваш логін та пароль</p>

                    <form class="fex-login__formAuth" method="post">
                        {% csrf_token %}
                        <div class="fex-form__group">
                            <input data-auto-bind="" class="fex-form__control" name="login" placeholder="Логин или телефон" type="text">
                            <div class="fex-form__error"></div>
                        </div>
                            <div class="fex-form__group">
                                <input data-auto-bind="" class="fex-form__control" name="password" placeholder="Пароль" type="password">
                                <div class="fex-form__error"></div>
                            </div>
                        <button class="fex-login__submitBtn">Увійти</button>
                    </form>

            </div>
        </div>
    </div>

</body>
</html>